openapi: '3.0.0'
info:
  title: 'Election Fraud Prevention API'
  version: '1.0.0'

paths:
  # User Features
  /api/users:
    post:
      summary: Create a new user by the party (LLA)
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created

  # User Roles and Identity
  /api/users/{id}/roles:
    get:
      summary: Get user roles
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Roles returned

  # Muestra Resultados PÃºblico
  /api/mesa/{id}:
    get:
      summary: Get Mesa Data
      responses:
        '200':
          description: Mesa data returned

  /api/mesas:
    get:
      summary: Search Mesas
      responses:
        '200':
          description: Mesas list

  # Denuncias
  /api/denuncias:
    get:
      summary: List or Search Denuncias
      responses:
        '200':
          description: Denuncias list

  /api/denuncia/{id}:
    get:
      summary: Get Specific Denuncia
      responses:
        '200':
          description: Denuncia data

  # Fiscal General to Fiscal Mesa
  /api/fiscalizar:
    post:
      summary: Fiscal general evaluates fiscal mesa
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Fiscalizar'
      responses:
        '201':
          description: Fiscalization recorded

  # Upload File
  /api/upload:
    post:
      summary: Upload a file to the server
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: File uploaded successfully
        '500':
          description: Internal server error

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        roles:
          type: array
          items:
            type: string
        whatsapp:
          type: string
        mesa_id:
          type: string
    Fiscalizar:
      type: object
      properties:
        imagen:
          type: string
        validado:
          type: boolean
        errores:
          type: boolean
        observaciones:
          type: string

security:
  BearerAuth:
    type: http
    scheme: bearer
